version: "3.3"

services:
  commentservicedb:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "commentservice_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "root"

  postservicedb:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "postservice_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "root"

  reviewservicedb:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "reviewservice_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "root"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8061:8061"
    depends_on:
      - config-service

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - discovery-service

  messaging-service:
    build:
      context: ./messaging-service
      dockerfile: Dockerfile
    ports:
      - "8079:8079"
    depends_on:
      - discovery-service
      - rabbitmq

  review-service:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - discovery-service
      - reviewservicedb

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
      - postservicedb

  comment-service:
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - commentservicedb