version: "3.3"

services:
  commentservicedb:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "commentservice_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - spring-cloud-network

  postservicedb:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "postservice_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - spring-cloud-network

  reviewservicedb:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "reviewservice_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - spring-cloud-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - spring-cloud-network

  config-service:
    build:
      context: .
      dockerfile: ./config-service/Dockerfile
    ports:
      - "8088:8088"
    networks:
      - spring-cloud-network

  discovery-service:
    build:
      context: .
      dockerfile: ./discovery-service/Dockerfile
    ports:
      - "8061:8061"
    depends_on:
      - config-service
    networks:
      - spring-cloud-network
    environment:
      - EUREKA_SERVER_PORT=8061
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/

  messaging-service:
    build:
      context: ./
      dockerfile: ./messaging-service/Dockerfile
    ports:
      - "8079:8079"
    depends_on:
      rabbitmq:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - spring-cloud-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq


  review-service:
    build:
      context: ./
      dockerfile: ./review-service/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - discovery-service
      - reviewservicedb
    networks:
      - spring-cloud-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/

  post-service:
    build:
      context: ./
      dockerfile: ./post-service/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
      - postservicedb
    networks:
      - spring-cloud-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/

  comment-service:
    build:
      context: ./
      dockerfile: ./comment-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - commentservicedb
    networks:
      - spring-cloud-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/

  gateway-service:
    build:
      context: ./
      dockerfile: ./gateway-service/Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - discovery-service
    networks:
      - spring-cloud-network
    environment:
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SERVER_PORT=8061
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/

networks:
  spring-cloud-network:
    driver: bridge